# Generated by Django 4.2.27 on 2026-03-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_userprofile_role_travelerprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelerprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="traveler_images/"
            ),
        ),
    ]
