# Generated by Django 4.2.27 on 2026-02-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(default="Web Inquiry", max_length=255),
        ),
    ]
