# Generated by Django 4.2.27 on 2026-02-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_contact_phone_alter_contact_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="subject",
        ),
    ]
