# Generated by Django 4.2.27 on 2026-02-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_remove_contact_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="subject",
            field=models.CharField(
                choices=[
                    ("General Inquiry", "General Inquiry"),
                    ("Booking Issue", "Booking Issue"),
                    ("AI Plan Problem", "AI Plan Problem"),
                    ("Feedback", "Feedback"),
                ],
                default="General Inquiry",
                max_length=100,
            ),
        ),
    ]
