# Generated by Django 4.2.27 on 2026-03-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itinerary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="saveditinerary",
            name="budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="saveditinerary",
            name="travelers",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="saveditinerary",
            name="starting_place",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
