# Generated by Django 4.2.27 on 2026-03-15 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuideProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="guide_images/"),
                ),
                ("bio", models.TextField(blank=True)),
                ("languages", models.JSONField(blank=True, default=list)),
                ("specialization", models.CharField(blank=True, max_length=200)),
                ("destinations", models.JSONField(blank=True, default=list)),
                ("experience_years", models.PositiveIntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
                ("tours_completed", models.PositiveIntegerField(default=0)),
                (
                    "availability",
                    models.CharField(
                        choices=[("available", "Available"), ("busy", "Busy")],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guide_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Guide Profile",
                "verbose_name_plural": "Guide Profiles",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("traveler_name", models.CharField(max_length=150)),
                ("traveler_email", models.EmailField(blank=True, max_length=254)),
                ("traveler_phone", models.CharField(blank=True, max_length=30)),
                ("destination", models.CharField(max_length=200)),
                ("trip_start", models.DateField()),
                ("trip_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("upcoming", "Upcoming"),
                            ("completed", "Completed"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="guides.guideprofile",
                    ),
                ),
                (
                    "traveler_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guide_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "ordering": ["-trip_start"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("assignment", "Assignment"),
                            ("accepted", "Accepted"),
                            ("request", "Request"),
                            ("completed", "Completed"),
                            ("upcoming", "Upcoming"),
                            ("rating", "Rating"),
                        ],
                        default="assignment",
                        max_length=30,
                    ),
                ),
                ("message", models.CharField(max_length=300)),
                ("highlight", models.CharField(blank=True, max_length=150)),
                ("sub", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="guides.guideprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "ordering": ["-created_at"],
            },
        ),
    ]
