# Generated by Django 4.2.27 on 2026-03-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0003_alter_activity_activity_type_alter_booking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("assignment", "Assignment"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("auto_rejected", "Auto Rejected"),
                    ("request", "Request"),
                    ("completed", "Completed"),
                    ("upcoming", "Upcoming"),
                    ("rating", "Rating"),
                ],
                default="assignment",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("rejected", "Rejected"),
                    ("auto_rejected", "Auto Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
