# Generated by Django 4.2.27 on 2026-03-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0004_alter_activity_activity_type_alter_booking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guideprofile",
            name="experience_years",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
