# Generated by Django 4.2.27 on 2026-04-06 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0005_alter_guideprofile_experience_years"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rating", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("booking", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="review", to="guides.booking")),
                ("guide", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="guides.guideprofile")),
                ("traveler", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="guide_reviews", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                check=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                name="guides_review_rating_between_1_and_5",
            ),
        ),
    ]
