# Generated by Django 4.2.27 on 2026-03-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoNameDestination",
            fields=[
                ("geoname_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "province",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("country_code", models.CharField(default="NP", max_length=10)),
                (
                    "category",
                    models.CharField(db_index=True, default="Sight", max_length=100),
                ),
            ],
        ),
    ]
