# Generated by Django 4.2.27 on 2026-03-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0002_geonamedestination"),
    ]

    operations = [
        migrations.AddField(
            model_name="geonamedestination",
            name="best_for",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="geonamedestination",
            name="highlights",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="geonamedestination",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="geonamedestination",
            name="popularity_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="geonamedestination",
            name="recommended_days",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="geonamedestination",
            name="short_description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
